"""khoi tao schema dataops

Revision ID: 6ccc8e79dbcd
Revises: 
Create Date: 2026-09-20 14:05:08.393101
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ccc8e79dbcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_key', sa.String(length=256), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity', 'entity_key'], unique=False)
    op.create_table('export_job',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gcs_path', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_current',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('number', sa.BigInteger(), nullable=False),
    sa.Column('market_share', sa.Float(), nullable=True),
    sa.Column('prev_number', sa.BigInteger(), nullable=True),
    sa.Column('prev_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('year', 'state', 'gender', 'name')
    )
    op.create_index('ix_fact_filter_sort', 'fact_current', ['state', 'year', 'gender', sa.literal_column('number DESC')], unique=False)
    op.create_index('ix_fact_name', 'fact_current', ['name'], unique=False)
    op.create_index('ix_fact_year_gender', 'fact_current', ['year', 'gender'], unique=False)
    op.create_table('fact_override',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'state', 'gender', 'name', 'field', name='uq_override_key')
    )
    op.create_index('ix_override_key', 'fact_override', ['year', 'state', 'gender', 'name'], unique=False)
    op.create_table('qc_exception',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=8), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('observed', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=320), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qc_key', 'qc_exception', ['year', 'state', 'gender', 'name'], unique=False)
    op.create_index('ix_qc_run', 'qc_exception', ['run_id'], unique=False)
    op.create_index('ix_qc_status_severity', 'qc_exception', ['status', 'severity'], unique=False)
    op.create_table('signed_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('signed_by', sa.String(length=320), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_run_id', sa.String(length=64), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_row_count', sa.BigInteger(), nullable=True),
    sa.Column('source_last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_row_count', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('scope_states', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    op.create_table('versions_sent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signed_version_id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=256), nullable=False),
    sa.Column('sent_by', sa.String(length=320), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['signed_version_id'], ['signed_version.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versions_sent')
    op.drop_table('app_role')
    op.drop_table('sync_state')
    op.drop_table('signed_version')
    op.drop_index('ix_qc_status_severity', table_name='qc_exception')
    op.drop_index('ix_qc_run', table_name='qc_exception')
    op.drop_index('ix_qc_key', table_name='qc_exception')
    op.drop_table('qc_exception')
    op.drop_index('ix_override_key', table_name='fact_override')
    op.drop_table('fact_override')
    op.drop_index('ix_fact_year_gender', table_name='fact_current')
    op.drop_index('ix_fact_name', table_name='fact_current')
    op.drop_index('ix_fact_filter_sort', table_name='fact_current')
    op.drop_table('fact_current')
    op.drop_table('export_job')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_user')
    # ### end Alembic commands ###
